# Generated by Django 4.1.5 on 2023-03-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_image_alter_news_thumbnail_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_time',
            new_name='comment_time',
        ),
    ]
